create_docs_paths: [
  'integrations/pytorch-lightning/Neptune-PyTorch-Lightning-basic.ipynb',
  'integrations/pytorch-lightning/Neptune-PyTorch-Lightning-advanced.ipynb',
  'integrations/xgboost/Neptune-XGBoost.ipynb',
  'product-tours/how-it-works/Neptune-API-Tour.ipynb',
  'quick-starts/first-experiment/Use-Neptune-API-to-log-your-first-experiment.ipynb',
  'quick-starts/monitor-ml-runs/Monitor-ML-runs-live.ipynb',
  'quick-starts/organize-ml-experimentation/Organize-ML-experiments.ipynb',
]

run_docs_paths:
  included_patterns: [
#    '/docs',
    '/tests',
#    '/showcase',
  ]
  excluded_patterns: [
    '/.ipynb_checkpoints',
    '/.git',
    '/integrations',
    'logging_snippets.ipynb',
    'Neptune-API-Tour.ipynb ',
    'Organize-ML-experiments.ipynb',
    'r-integration.ipynb',
    'Use-Neptune-API-to-log-your-first-experiment.ipynb',
    'Monitor-ML-runs-live.ipynb',
    'neptune_test_run.ipynb',
    'pytorch_lightning-integration.ipynb',
    'Template.ipynb',
    'xgboost-integration.ipynb',
  ]
